language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pawelklejka/airlines-frontend -f Dockerfiler.dev .

script:
  - docker run -e CI=true pawelklejka/airlines-frontend npm run test
