language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pawelklejka/airlines-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true pawelklejka/airlines-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "airlines-frontend"
  env: "AirlinesFrontend-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-478729113206"
  bucket_path: "airlines-frontend"
  on:
    branches:
      only:
      - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
