export const MONOLITH = "http://localhost:8081"
export const MICROSERVICE_GATEWAY ="http://localhost:9000"
export const FLIGHT_SERVICE= `${MICROSERVICE_GATEWAY}/FLIGHT-SERVICE`
export const TOURIST_SERVICE= `${MICROSERVICE_GATEWAY}/TOURIST-SERVICE`
export const TICKET_SERVICE= `${MICROSERVICE_GATEWAY}/TICKET-SERVICE`